### ISSUE TITLE
error during rebuilding the project to create .dll

### ISSUE THREAD

**Issue by mnshadat** [oysstu/LabVIEW-libsvm#2]
I am getting linker error for 'libsvm.lib'. Could you please help me to rebuild the dll?

error LNK1181: cannot open input file 'libsvm.lib'

Thanks in advance.

**Comment by oysstu** [comment]
The LabVIEW wrapper depends on a statically compiled library of libsvm. The linker error you got typically means that the linker cannot find that library at the expected path. 

The default expected path is "C:\dev\libsvm-320" on windows, but can be changed in the property file "cpp\LabVIEW-libsvm\Paths.props". Perhaps less obvious is that it expects the lib file to be in a subfolder called either windows_x86 or windows_x86_64 depending on the bitness.

Compiling libsvm statically can be done by running the corresponding bat files (under dependencies)  from the root libsvm folder. This also creates the correct output folders.

Let me know how it goes. I might streamline the process on windows in the future.

**Comment by mnshadat** [comment]
Thanks for your feedback. Basically the batch file was unable to create the static library libsvm.lib for some reason. I am using the same directory structure C:\dev\libsvm-321. Even though it was failing.

I ended up creating my own VS project to create the static library libsvm.lib. I also copied the library to the  sub-folder of the cpp labview wrapper. After that it is working perfectly and I am able to create my own .dll.

Again thank you so much for your feedback and contribution. I really appreciate it.

**Comment by oysstu** [comment]
Not sure why the batch file would fail, the only thing I can think of is that you're using a different version of visual studio. As I wrote, I'll probably change the build system to be more self-contained instead of using static libs, as the external dependencies are quite small.
