### ISSUE TITLE
error when run training for epsilon-SVR

### ISSUE THREAD

**Issue by zhenxuanjameszhang** [oysstu/LabVIEW-libsvm#3]
Hi,

I used LibSVM Dense Train.vi (Epsion-SVR) in my project, All the result  is consistent with the model generated by MATLAB LibSVM library. Specifically, I noticed that the Model that it generated has nSV as empty. 

When I use svmdense_predict.vi (Predict), it generate error message "Uninitialized model passed to libsvm". I located this error code in 
LabVIEW-libsvm/cpp/LabVIEW-libsvm-dense/LabVIEW-libsvm-dense.cpp
in line 437. 

I suspect that it is because the model created by LibSVM Dense Train.vi (Epsilon-SVR) has nSV as empty. (see line 436 checking if nSV is empty, throw error if it is empty) 

I will appreciate it if you can take a look. Since I am not an expert in LibSVM implementation, I am not certain how to handle nSV in case of regression prediction. 

Thanks in advance

**Comment by oysstu** [comment]
I'll take a look this weekend. I'm not surprised if there's some bugs when using regression, as it hasn't been tested extensively.

**Comment by oysstu** [comment]
It seems to simply be a case of libsvm not utilizing the nSV parameter for regression, as there's only one class anyway. I removed the check for non-empty nSV as the check for the support vectors should be sufficient. I'll upload a new version. You can also circumvent it easily by manually setting the nSV model parameter equal to the number of support vectors (size of indices, or l).

**Comment by zhenxuanjameszhang** [comment]
I updated to the new release v1.0 and I believe that you have fixed the issue. Thank you.
