### ISSUE TITLE
Problem Using LabVIEW-libsvm

### ISSUE THREAD

**Issue by djf321** [oysstu/LabVIEW-libsvm#4]
I have been having difficulties getting it installed in Labview 2015 64-bit. This is my first time installing a labview library, and I am not sure if the problems I have been having is due to my inexperience. I downloaded the .zip file from github. Then double clicked LVLibSVM.vipb in the folder titled VIPM Build. Then I used the VI Package Manager to build and install libsvm. Everything seemed to work fine until I tried to use one of the examples. I opened LVLibSVM.lvproj in the folder titled LabVIEW. And then I went to LibSVM DenseExamplesSVMDense_Crossvalidation_FromFile.vi. When I opened this vi though it said that it can’t find LabVIEW-libsvm-dense.dll. For some reason it can’t find the .dll files needed to run this example. And I can’t seem to find the .dll file anywhere in the downloaded directory. How do I go about fixing this problem? Any advice you could provide is appreciated.

**Comment by oysstu** [comment]
Look in the release page on github and use the .vip file instead, it contains the binaries. The build file is used to package the library, not to install into labview. 

Edit: Updated the installation steps on the front page, as you're not the first to misunderstand them
