### ISSUE TITLE
graph labels in SVMDense_GridSearch_FromFile.vi

### ISSUE THREAD

**Issue by torekp** [oysstu/LabVIEW-libsvm#5]
Hi oysstu,
Great code!  Just a little detail I noticed, SVMDense_GridSearch_FromFile.vi has the labels C and gamma reversed on its graph.  And its subVI Gridsearch Visualization.  And SVM_GridSerach_From File.  The selection of the optimal C, gamma pair is still correct.

**Comment by oysstu** [comment]
Hi torekp, thanks for the feedback. I'm not up and running with LabVIEW 2015 on windows at the moment, but I'll implement this quick fix soon. I'll leave it open until I do for visibility.

**Comment by oysstu** [comment]
Fixed in the latest release
