### ISSUE TITLE
Is there a detailed manual for libsvm in LabVIEW?

### ISSUE THREAD

**Issue by Forgetwan** [oysstu/LabVIEW-libsvm#7]
Hi oysstu,I am a graduate student from Hefei University of Technology.I need to use the libsvm module in LabVIEW, but I am having some problems with it. Do you have a detailed introduction to the use of this module?

**Comment by oysstu** [comment]
Please have a look at the examples distributed with each interface. They show some basic usage of the library. The next step is to learn from the libsvm documentation, as these VIs are thin wrappers around the functions defined in the main library.

See also [A Practical Guide to Support Vector Classification](https://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf)
